extends:
  - ./.eslintrc.yaml

parserOptions:
  sourceType: 'module'
  project: 'test/tsconfig.json'

rules:
  '@typescript-eslint/no-explicit-any': 'off'
  'no-unused-vars': 'off'
  '@typescript-eslint/no-unused-vars': 'error'
  '@typescript-eslint/no-empty-function': 'off'
