name: Test

on:
  workflow_call:

jobs:
  integration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example
          POSTGRES_DB: test_integration
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      localstack:
        image: localstack/localstack
        env:
          SERVICES: s3
          DEFAULT_REGION: ap-northeast-1
          DATA_DIR: /tmp/localstack/data
        ports: [ "4566:4566" ]
    steps:
      - name: Install Git
        shell: sh
        run: |
          sudo apt update
          sudo apt install -y git
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
      - name: Install Yarn
        run: npm i -g yarn
      - name: Install modules
        run: yarn --immutable
      - name: Migrate database
        uses: ariga/atlas-deploy-action@v0
        with:
          url: postgres://postgres:example@postgres:5432/test_integration?search_path=public&sslmode=disable
          dir: db/migrations
      - name: Run Integration Tests
        run: yarn test
        env:
          DATABASE_HOST: localhost
          DATABASE_NAME: test_integration
          TEST_DATABASE_HOST: localhost
          TEST_DATABASE_NAME: test_integration
          DEFAULT_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: localstack
          AWS_SECRET_ACCESS_KEY: localstack
